export const GET_TODOS='GET_TODOS';
export const FILTER_TASK_PRIORITY='FILTER_TASK_PRIORITY';
export const FILTER_TASK_CATEGORY='FILTER_TASK_CATEGORY';
export const FILTER_TASK_STATUS='FILTER_TASK_STATUS';
export const FILTER_TASKNAME_SEARCH='FILTER_TASK_SEARCH';
export const FILTER_TASKDUEDATE_SEARCH='FILTER_TASKDUEDATE_SEARCH';
export const GET_TODO_DETAIL='GET_TODO_DETAIL';